version: '2'
services:
  jhipstersampleapplication55-app:
    image: jhipstersampleapplication55
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://jhipstersampleapplication55-mssql:1433;database=jhipsterSampleApplication55
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstersampleapplication55-mssql:
    extends:
      file: mssql.yml
      service: jhipstersampleapplication55-mssql
